# Generated by Django 4.0.5 on 2023-02-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('linkName', models.TextField()),
                ('activeDays', models.TextField()),
                ('NumberOfcolumn', models.TextField()),
                ('fieldName', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.TextField()),
                ('data2', models.TextField()),
                ('data3', models.TextField()),
                ('data4', models.TextField()),
                ('data5', models.TextField()),
                ('data6', models.TextField()),
                ('data7', models.TextField()),
                ('data8', models.TextField()),
                ('data9', models.TextField()),
                ('linkName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenerateLink.generatelink')),
            ],
        ),
    ]
