# Generated by Django 4.0.5 on 2023-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerateLink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='data10',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='data11',
            field=models.TextField(default=''),
        ),
    ]
