# Generated by Django 4.0.5 on 2023-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
