# Generated by Django 4.0.5 on 2023-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.EmailField(max_length=254)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
