# Generated by Django 4.0.5 on 2023-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0002_dev_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
