# Generated by Django 4.0.5 on 2023-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0003_dev_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='img',
            field=models.ImageField(default='', upload_to='media/dev/'),
        ),
    ]
